// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChooseDestinationFolder():Promise<string>;

export function GetMediaFilesForVolume(arg1:string):Promise<Array<main.MediaFile>>;

export function VolumesFromGetfsstat():Promise<Array<string>>;
