// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseDestinationFolder() {
  return window['go']['main']['App']['ChooseDestinationFolder']();
}

export function GetMediaFilesForVolume(arg1) {
  return window['go']['main']['App']['GetMediaFilesForVolume'](arg1);
}

export function VolumesFromGetfsstat() {
  return window['go']['main']['App']['VolumesFromGetfsstat']();
}
