// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckIfFilesAlreadyExported(arg1, arg2) {
  return window['go']['main']['App']['CheckIfFilesAlreadyExported'](arg1, arg2);
}

export function ChooseDestinationFolder() {
  return window['go']['main']['App']['ChooseDestinationFolder']();
}

export function ExportFiles(arg1, arg2) {
  return window['go']['main']['App']['ExportFiles'](arg1, arg2);
}

export function GetDefaultExportDestination() {
  return window['go']['main']['App']['GetDefaultExportDestination']();
}

export function GetMediaFilesForVolume(arg1) {
  return window['go']['main']['App']['GetMediaFilesForVolume'](arg1);
}

export function ShowFileInFilesystem(arg1) {
  return window['go']['main']['App']['ShowFileInFilesystem'](arg1);
}

export function VolumesFromGetfsstat() {
  return window['go']['main']['App']['VolumesFromGetfsstat']();
}
