// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMediaFilesForVolume(arg1:string):Promise<Array<string>>;

export function VolumesFromGetfsstat():Promise<Array<string>>;
