// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckIfFilesAlreadyExported(arg1:Array<main.MediaFile>,arg2:string):Promise<Array<main.MediaFile>>;

export function ChooseDestinationFolder():Promise<string>;

export function ExportFiles(arg1:Array<string>,arg2:string):Promise<void>;

export function GetMediaFilesForVolume(arg1:string):Promise<Array<main.MediaFile>>;

export function VolumesFromGetfsstat():Promise<Array<string>>;
